/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Calculator;



/**
 *
 * @author Ian Christopher
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textField1 = new java.awt.TextField();
        jTextField1 = new javax.swing.JTextField();
        jdntBS = new javax.swing.JButton();
        jdntCE = new javax.swing.JButton();
        jdntC = new javax.swing.JButton();
        jdntButton7 = new javax.swing.JButton();
        jdntButton8 = new javax.swing.JButton();
        jdntButton9 = new javax.swing.JButton();
        jdntPLUS = new javax.swing.JButton();
        jdntButton4 = new javax.swing.JButton();
        jdntButton5 = new javax.swing.JButton();
        jdntButton6 = new javax.swing.JButton();
        jdntMINUS = new javax.swing.JButton();
        jdntButton1 = new javax.swing.JButton();
        jdntButton2 = new javax.swing.JButton();
        jdntButton3 = new javax.swing.JButton();
        jdntPM = new javax.swing.JButton();
        jdntButton0 = new javax.swing.JButton();
        jdntDOT = new javax.swing.JButton();
        jdntEQUAL = new javax.swing.JButton();
        jdntMULTIPLY = new javax.swing.JButton();
        jdntDIV2 = new javax.swing.JButton();

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(310, 420));
        setPreferredSize(new java.awt.Dimension(310, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 40));

        jdntBS.setFont(new java.awt.Font("Wingdings", 1, 24)); // NOI18N
        jdntBS.setText("");
        jdntBS.setToolTipText("");
        jdntBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntBSActionPerformed(evt);
            }
        });
        getContentPane().add(jdntBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 65, 60));

        jdntCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntCE.setText("CE");
        jdntCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntCEActionPerformed(evt);
            }
        });
        getContentPane().add(jdntCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 65, 60));

        jdntC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntC.setText("C");
        jdntC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntCActionPerformed(evt);
            }
        });
        getContentPane().add(jdntC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 65, 60));

        jdntButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton7.setText("7");
        jdntButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 65, 60));

        jdntButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton8.setText("8");
        jdntButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 65, 60));

        jdntButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton9.setText("9");
        jdntButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 65, 60));

        jdntPLUS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntPLUS.setText("+");
        jdntPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntPLUSActionPerformed(evt);
            }
        });
        getContentPane().add(jdntPLUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 65, 60));

        jdntButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton4.setText("4");
        jdntButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 65, 60));

        jdntButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton5.setText("5");
        jdntButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 65, 60));

        jdntButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton6.setText("6");
        jdntButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 65, 60));

        jdntMINUS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntMINUS.setText("-");
        jdntMINUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntMINUSActionPerformed(evt);
            }
        });
        getContentPane().add(jdntMINUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 65, 60));

        jdntButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton1.setText("1");
        jdntButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 65, 60));

        jdntButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton2.setText("2");
        jdntButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 65, 60));

        jdntButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton3.setText("3");
        jdntButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 65, 60));

        jdntPM.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntPM.setText("±");
        jdntPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntPMActionPerformed(evt);
            }
        });
        getContentPane().add(jdntPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 65, 60));

        jdntButton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntButton0.setText("0");
        jdntButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 65, 60));

        jdntDOT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntDOT.setText(".");
        jdntDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntDOTActionPerformed(evt);
            }
        });
        getContentPane().add(jdntDOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 65, 60));

        jdntEQUAL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntEQUAL.setText("=");
        jdntEQUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntEQUALActionPerformed(evt);
            }
        });
        getContentPane().add(jdntEQUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 65, 60));

        jdntMULTIPLY.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntMULTIPLY.setText("*");
        jdntMULTIPLY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntMULTIPLYActionPerformed(evt);
            }
        });
        getContentPane().add(jdntMULTIPLY, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 65, 60));

        jdntDIV2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdntDIV2.setText("/");
        jdntDIV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdntDIV2ActionPerformed(evt);
            }
        });
        getContentPane().add(jdntDIV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 65, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void EnterNumbers(String q)
    {
        String Nums = jTextField1.getText() + q;
        jTextField1.setText(Nums);
    }
            
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jdntCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntCActionPerformed
      jTextField1.setText("");
    }//GEN-LAST:event_jdntCActionPerformed

    private void jdntBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntBSActionPerformed
     String backSp = null;
     
     if(jTextField1.getText().length() > 0)
     {
         StringBuilder sb = new  StringBuilder(jTextField1.getText());    
         sb.deleteCharAt(jTextField1.getText().length() - 1);
         backSp = sb.toString();
         jTextField1.setText(backSp);
     }
    }//GEN-LAST:event_jdntBSActionPerformed

    private void jdntPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntPLUSActionPerformed
        NumEnter1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "+";
    }//GEN-LAST:event_jdntPLUSActionPerformed

    private void jdntButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton7ActionPerformed
       EnterNumbers("7");
    }//GEN-LAST:event_jdntButton7ActionPerformed

    private void jdntCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntCEActionPerformed
      jTextField1.setText("");
      
      String Fn, Sn;
      
      Fn = String.valueOf(NumEnter1);
      Sn = String.valueOf(NumEnter2);
      
      Fn ="";
      Sn ="";
    }//GEN-LAST:event_jdntCEActionPerformed

    private void jdntButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton2ActionPerformed
     EnterNumbers("2");
    }//GEN-LAST:event_jdntButton2ActionPerformed

    private void jdntButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton8ActionPerformed
       EnterNumbers("8");
    }//GEN-LAST:event_jdntButton8ActionPerformed

    private void jdntButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton9ActionPerformed
      EnterNumbers("9");
    }//GEN-LAST:event_jdntButton9ActionPerformed

    private void jdntButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton4ActionPerformed
       EnterNumbers("4");
    }//GEN-LAST:event_jdntButton4ActionPerformed

    private void jdntButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton5ActionPerformed
       EnterNumbers("5");
    }//GEN-LAST:event_jdntButton5ActionPerformed

    private void jdntButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton6ActionPerformed
       EnterNumbers("6");
    }//GEN-LAST:event_jdntButton6ActionPerformed

    private void jdntButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton1ActionPerformed
      EnterNumbers("1");
    }//GEN-LAST:event_jdntButton1ActionPerformed

    private void jdntButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton3ActionPerformed
     EnterNumbers("3");
    }//GEN-LAST:event_jdntButton3ActionPerformed

    private void jdntButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntButton0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jdntButton0ActionPerformed

    private void jdntMULTIPLYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntMULTIPLYActionPerformed
        NumEnter1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "*";
    }//GEN-LAST:event_jdntMULTIPLYActionPerformed

    private void jdntMINUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntMINUSActionPerformed
        NumEnter1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        op = "-";
    }//GEN-LAST:event_jdntMINUSActionPerformed

    private void jdntPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntPMActionPerformed
     
        double nums = Double.parseDouble(String.valueOf(jTextField1.getText()));
        nums = nums * (-1);
        jTextField1.setText(String.valueOf(nums ));
    }//GEN-LAST:event_jdntPMActionPerformed

    private void jdntDOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntDOTActionPerformed
        if (! jTextField1.getText().contains("."))
        {
            jTextField1.setText( jTextField1.getText() + jdntDOT.getText());
        }
    }//GEN-LAST:event_jdntDOTActionPerformed

    private void jdntEQUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntEQUALActionPerformed
       NumEnter2 = Double.parseDouble(jTextField1.getText());
       if (op == "+")
       {
           Result = NumEnter1 + NumEnter2;
            jTextField1.setText(String.valueOf(Result));
       }
       else if (op == "-")
        {
           Result = NumEnter1 - NumEnter2;
            jTextField1.setText(String.valueOf(Result));
       }
       else if (op == "*")
        {
           Result = NumEnter1 * NumEnter2;
            jTextField1.setText(String.valueOf(Result));
       }
         
       else if (op == "/")
        {
           Result = NumEnter1 / NumEnter2;
            jTextField1.setText(String.valueOf(Result));
       }
    }//GEN-LAST:event_jdntEQUALActionPerformed

    private void jdntDIV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdntDIV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdntDIV2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jdntBS;
    private javax.swing.JButton jdntButton0;
    private javax.swing.JButton jdntButton1;
    private javax.swing.JButton jdntButton2;
    private javax.swing.JButton jdntButton3;
    private javax.swing.JButton jdntButton4;
    private javax.swing.JButton jdntButton5;
    private javax.swing.JButton jdntButton6;
    private javax.swing.JButton jdntButton7;
    private javax.swing.JButton jdntButton8;
    private javax.swing.JButton jdntButton9;
    private javax.swing.JButton jdntC;
    private javax.swing.JButton jdntCE;
    private javax.swing.JButton jdntDIV2;
    private javax.swing.JButton jdntDOT;
    private javax.swing.JButton jdntEQUAL;
    private javax.swing.JButton jdntMINUS;
    private javax.swing.JButton jdntMULTIPLY;
    private javax.swing.JButton jdntPLUS;
    private javax.swing.JButton jdntPM;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
